services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - webapi:/app/
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=clean-architecture;Username=postgres;Password=1234
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - Jwt__Secret=YOUR_SECURE_GENERATED_SECRET
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=clean-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      # - ./.containers/db:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  # seq:
  #   image: datalust/seq:2024.3
  #   container_name: seq
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - 8081:5341



volumes:
  postgres_data: # Declares the named volume 'postgres_data'
  webapi: